services:
  quizzle:
    container_name: quizzle
    image: quizzle:1.3.1
    build:
      context: .
    ports: 
      - ${quizzlePort:-80}:8080
      - ${wsPort:-8000}:8000
    environment:
      - publicPort=${quizzlePort:-80}
      - wsPort=${wsPort:-8000}
      - PGUSER=quizzleAdmin
      - PGDATABASE=quizzleDB
      - PGPASSWORD=12345
      - PGHOST=database
    depends_on:
      - database
    volumes:
    - env:/usr/src/app/quiz

  database:
    container_name: database
    image: 'postgres:14'
    environment:
    - POSTGRES_USER=quizzleAdmin
    - POSTGRES_PASSWORD=12345
    - POSTGRES_DB=quizzleDB
    volumes:
    - ./initscripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    - dbvol:/var/lib/postgresql/data
volumes:
  dbvol: {}
  env: {}
  
